-- V35 - Group the tutorial catalog into domains.
--
-- The catalog grew to several hundred lessons, so learners need a way to browse by
-- subject rather than scanning one flat list. Each tutorial belongs to exactly one
-- category; the mapping is exhaustive over the published catalog.

CREATE TABLE tutorial_category (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    slug VARCHAR(120) NOT NULL UNIQUE,
    name VARCHAR(160) NOT NULL,
    description TEXT NOT NULL,
    sort_order INTEGER NOT NULL CHECK (sort_order > 0),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE tutorial
    ADD COLUMN category_id UUID REFERENCES tutorial_category (id) ON DELETE SET NULL;

CREATE INDEX tutorial_category_id_idx ON tutorial (category_id);

INSERT INTO tutorial_category (slug, name, description, sort_order)
VALUES
    ('java-core', 'Java Core', 'The language itself: types, collections, generics, streams, and the object model.', 1),
    ('jdk-and-toolchain', 'JDK and Toolchain', 'Install, configure, and understand the JDK, its tools, and its release model.', 2),
    ('jvm-internals', 'JVM Internals', 'How bytecode, memory, the garbage collector, and the JIT actually run your code.', 3),
    ('concurrency', 'Concurrency', 'Threads, executors, locks, virtual threads, and the patterns that keep them safe.', 4),
    ('build-engineering', 'Build Engineering', 'Maven and Gradle: lifecycles, dependencies, multi-module builds, and reproducibility.', 5),
    ('spring-core', 'Spring Framework', 'The Spring container, configuration, AOP, web layer, and the 6 to 7 upgrade story.', 6),
    ('spring-data-and-security', 'Spring Data and Security', 'Persistence, transactions, caching, batch, messaging, and securing Spring services.', 7),
    ('databases', 'Databases and SQL', 'SQL, PostgreSQL, schema design, indexes, transactions, and operational database work.', 8),
    ('persistence', 'JPA and Hibernate', 'Object-relational mapping: mapping, loading, caching, locking, and batching.', 9),
    ('messaging-and-events', 'Messaging and Events', 'Kafka, JMS, and event-driven design: delivery guarantees, schemas, and sagas.', 10),
    ('integration', 'Enterprise Integration', 'Wiring systems together: integration frameworks, batch, scheduling, and protocols.', 11),
    ('api-design', 'API Design', 'REST, GraphQL, and gRPC contracts, versioning, errors, and developer experience.', 12),
    ('http-and-networking', 'HTTP and Networking', 'Protocol mechanics: methods, caching, TLS, connections, proxies, and debugging.', 13),
    ('microservices', 'Microservices', 'Service resilience, distributed data, and multi-service operations.', 14),
    ('architecture', 'Architecture', 'System shape, boundaries, decision records, and long-term design economics.', 15),
    ('domain-driven-design', 'Domain-Driven Design', 'Model the business: language, bounded contexts, aggregates, and events.', 16),
    ('testing', 'Testing', 'Unit, integration, and contract testing with the tooling that makes them reliable.', 17),
    ('quality-and-static-analysis', 'Quality and Static Analysis', 'Coverage, mutation testing, linting, benchmarks, and load testing as gates.', 18),
    ('observability', 'Observability', 'Metrics, logs, traces, alerting, and debugging production with evidence.', 19),
    ('performance', 'Performance and Caching', 'Measure and cache deliberately: profiling, allocation, and invalidation.', 20),
    ('reactive', 'Reactive Programming', 'Project Reactor, WebFlux, R2DBC, and when reactive beats plain blocking code.', 21),
    ('containers-and-kubernetes', 'Containers and Kubernetes', 'Images, registries, deployments, probes, scaling, and running Java on Kubernetes.', 22),
    ('cloud-and-delivery', 'Cloud and Delivery', 'CI/CD, progressive rollout, infrastructure as code, and cloud service choices.', 23),
    ('security', 'Security', 'OWASP risks, authentication, secrets, crypto, and supply-chain hardening.', 24),
    ('data-formats', 'Data Formats', 'JSON, XML, YAML, Protobuf, Avro, and safe serialization across boundaries.', 25),
    ('algorithms', 'Algorithms and Data Structures', 'Complexity, core data structures, and the patterns that show up in real code.', 26),
    ('refactoring-and-legacy', 'Refactoring and Legacy Code', 'Change code safely: seams, characterization tests, debt, and modernization paths.', 27),
    ('engineering-practice', 'Engineering Practice', 'Reviews, estimation, incident learning, onboarding, growth, and collaboration.', 28)
ON CONFLICT (slug) DO UPDATE
    SET name = EXCLUDED.name,
        description = EXCLUDED.description,
        sort_order = EXCLUDED.sort_order;

UPDATE tutorial SET category_id = c.id
FROM tutorial_category c, (VALUES
    ('java-core', 'java-types-and-variables'),
    ('java-core', 'methods-and-control-flow'),
    ('java-core', 'strings-and-text'),
    ('java-core', 'dates-and-time'),
    ('java-core', 'classes-and-encapsulation'),
    ('java-core', 'collections'),
    ('java-core', 'enums-and-records'),
    ('java-core', 'exception-design'),
    ('java-core', 'java-generics-in-depth'),
    ('java-core', 'java-streams-in-depth'),
    ('java-core', 'java-optional-patterns'),
    ('java-core', 'java-functional-interfaces'),
    ('java-core', 'java-records-in-depth'),
    ('java-core', 'java-immutability-patterns'),
    ('java-core', 'java-text-blocks'),
    ('java-core', 'java-var-and-type-inference'),
    ('java-core', 'java-pattern-matching'),
    ('java-core', 'java-sealed-types'),
    ('java-core', 'java-reflection-and-annotations'),
    ('java-core', 'java-nio-and-file-io'),
    ('java-core', 'solid-principles-in-java'),
    ('java-core', 'dependency-injection'),
    ('jdk-and-toolchain', 'jdk-vs-jre-vs-jvm'),
    ('jdk-and-toolchain', 'installing-a-jdk'),
    ('jdk-and-toolchain', 'jdk-distributions-compared'),
    ('jdk-and-toolchain', 'java-release-cadence'),
    ('jdk-and-toolchain', 'choosing-a-java-version'),
    ('jdk-and-toolchain', 'java-home-and-path'),
    ('jdk-and-toolchain', 'jdk-command-line-tools'),
    ('jdk-and-toolchain', 'jshell-quick-experiments'),
    ('jdk-and-toolchain', 'classpath-vs-modulepath'),
    ('jdk-and-toolchain', 'java-module-system-basics'),
    ('jdk-and-toolchain', 'packaging-java-applications'),
    ('jdk-and-toolchain', 'migrating-between-java-lts'),
    ('jdk-and-toolchain', 'jvm-alternatives-today'),
    ('jdk-and-toolchain', 'jvm-ecosystem-and-distributions'),
    ('jdk-and-toolchain', 'long-term-java-strategy'),
    ('jdk-and-toolchain', 'kotlin-for-java-developers'),
    ('jdk-and-toolchain', 'kotlin-idioms-that-help-java-teams'),
    ('jdk-and-toolchain', 'scala-and-jvm-language-overview'),
    ('jdk-and-toolchain', 'jvm-language-interoperability'),
    ('jvm-internals', 'jvm-architecture-internals'),
    ('jvm-internals', 'garbage-collection-basics'),
    ('jvm-internals', 'gc-tuning-in-practice'),
    ('jvm-internals', 'jit-compilation-and-warmup'),
    ('jvm-internals', 'jvm-diagnostics-toolbox'),
    ('jvm-internals', 'debugging-java-in-the-ide'),
    ('jvm-internals', 'startup-time-engineering'),
    ('jvm-internals', 'class-data-sharing-and-appcds'),
    ('jvm-internals', 'java-performance-methodology'),
    ('jvm-internals', 'throughput-vs-latency'),
    ('jvm-internals', 'memory-profiling-in-practice'),
    ('jvm-internals', 'profiling-cpu-hotspots'),
    ('jvm-internals', 'jvm-vs-native-tradeoffs'),
    ('jvm-internals', 'graalvm-native-image-basics'),
    ('jvm-internals', 'native-image-with-spring-boot'),
    ('jvm-internals', 'reflection-and-dynamic-features-in-native'),
    ('jvm-internals', 'native-image-testing-and-profiling'),
    ('concurrency', 'concurrency-primitives'),
    ('concurrency', 'thread-lifecycle-and-diagnostics'),
    ('concurrency', 'executor-service-patterns'),
    ('concurrency', 'future-and-completablefuture'),
    ('concurrency', 'java-completable-future'),
    ('concurrency', 'thread-safety-by-design'),
    ('concurrency', 'locks-vs-synchronized'),
    ('concurrency', 'atomics-and-cas'),
    ('concurrency', 'java-locks-and-atomics'),
    ('concurrency', 'concurrent-collections-in-practice'),
    ('concurrency', 'virtual-threads-in-practice'),
    ('concurrency', 'java-virtual-threads'),
    ('concurrency', 'structured-concurrency-preview'),
    ('concurrency', 'java-structured-concurrency'),
    ('concurrency', 'parallel-streams-and-forkjoin'),
    ('concurrency', 'threadlocal-and-context-propagation'),
    ('concurrency', 'deadline-and-timeout-propagation'),
    ('concurrency', 'deadlock-livelock-detection'),
    ('concurrency', 'backpressure-and-flow-control'),
    ('concurrency', 'async-vs-sync-tradeoffs'),
    ('build-engineering', 'maven-quickstart-and-conventions'),
    ('build-engineering', 'maven-pom-anatomy'),
    ('build-engineering', 'maven-build-lifecycle-and-phases'),
    ('build-engineering', 'maven-dependency-scopes'),
    ('build-engineering', 'maven-transitive-dependencies-and-exclusions'),
    ('build-engineering', 'maven-dependency-management-and-boms'),
    ('build-engineering', 'maven-plugins-and-executions'),
    ('build-engineering', 'maven-surefire-and-failsafe'),
    ('build-engineering', 'maven-multi-module-builds'),
    ('build-engineering', 'maven-profiles-and-properties'),
    ('build-engineering', 'maven-settings-and-repositories'),
    ('build-engineering', 'maven-wrapper-and-version-pinning'),
    ('build-engineering', 'maven-toolchains'),
    ('build-engineering', 'maven-reproducible-builds'),
    ('build-engineering', 'maven-release-and-versioning'),
    ('build-engineering', 'maven-enforcer-and-quality-gates'),
    ('build-engineering', 'gradle-quickstart-and-structure'),
    ('build-engineering', 'gradle-kotlin-dsl'),
    ('build-engineering', 'gradle-tasks-and-build-lifecycle'),
    ('build-engineering', 'gradle-plugins'),
    ('build-engineering', 'gradle-dependency-configurations'),
    ('build-engineering', 'gradle-version-catalogs'),
    ('build-engineering', 'gradle-multi-project-builds'),
    ('build-engineering', 'gradle-jvm-toolchains'),
    ('build-engineering', 'gradle-testing-and-junit5'),
    ('build-engineering', 'gradle-incremental-builds-and-caching'),
    ('build-engineering', 'gradle-configuration-cache'),
    ('build-engineering', 'gradle-wrapper-and-version-alignment'),
    ('build-engineering', 'gradle-publishing-libraries'),
    ('build-engineering', 'migrating-maven-to-gradle'),
    ('build-engineering', 'gradle-vs-maven'),
    ('spring-core', 'spring-ecosystem-and-boot-overview'),
    ('spring-core', 'spring-ioc-container'),
    ('spring-core', 'spring-dependency-injection-patterns'),
    ('spring-core', 'spring-bean-lifecycle-and-scopes'),
    ('spring-core', 'spring-stereotypes-and-component-scanning'),
    ('spring-core', 'spring-configuration-properties-and-profiles'),
    ('spring-core', 'spring-autoconfiguration-and-conditional-beans'),
    ('spring-core', 'spring-application-events'),
    ('spring-core', 'spring-aop-fundamentals'),
    ('spring-core', 'spring-validation-and-binding'),
    ('spring-core', 'spring-mvc-request-handling'),
    ('spring-core', 'spring-rest-controllers-and-content-negotiation'),
    ('spring-core', 'spring-error-handling-and-problem-details'),
    ('spring-core', 'spring-http-clients'),
    ('spring-core', 'spring-testing-slices'),
    ('spring-core', 'spring-actuator-basics'),
    ('spring-core', 'spring-framework-7-overview'),
    ('spring-core', 'spring-boot-4-overview'),
    ('spring-core', 'migrating-spring-boot-3-to-4'),
    ('spring-core', 'spring-7-null-safety-jspecify'),
    ('spring-core', 'spring-7-api-versioning'),
    ('spring-core', 'spring-7-resilience-features'),
    ('spring-core', 'spring-jackson-3-integration'),
    ('spring-core', 'spring-aot-and-native-images'),
    ('spring-core', 'spring-modulith'),
    ('spring-core', 'spring-observability-and-tracing'),
    ('spring-core', 'spring-virtual-threads'),
    ('spring-core', 'spring-boot-testcontainers'),
    ('spring-core', 'spring-graphql-basics'),
    ('spring-core', 'spring-websockets'),
    ('spring-data-and-security', 'spring-data-jpa-repositories'),
    ('spring-data-and-security', 'spring-data-jpa-queries'),
    ('spring-data-and-security', 'spring-jdbc-and-jdbctemplate'),
    ('spring-data-and-security', 'spring-transaction-management'),
    ('spring-data-and-security', 'spring-flyway-migrations'),
    ('spring-data-and-security', 'spring-security-filter-chain'),
    ('spring-data-and-security', 'spring-security-authentication'),
    ('spring-data-and-security', 'spring-security-method-authorization'),
    ('spring-data-and-security', 'spring-oauth2-resource-server'),
    ('spring-data-and-security', 'spring-cache-abstraction'),
    ('spring-data-and-security', 'spring-scheduling-and-async'),
    ('spring-data-and-security', 'spring-retry-and-backoff'),
    ('spring-data-and-security', 'spring-batch-basics'),
    ('spring-data-and-security', 'spring-kafka-essentials'),
    ('spring-data-and-security', 'spring-http-interface-clients'),
    ('databases', 'sql-query-fundamentals'),
    ('databases', 'sql-joins-in-depth'),
    ('databases', 'sql-aggregations-and-window-functions'),
    ('databases', 'sql-indexing-strategy'),
    ('databases', 'sql-query-planner-and-explain'),
    ('databases', 'sql-transactions-and-locking'),
    ('databases', 'sql-constraints-and-integrity'),
    ('databases', 'sql-normalization-and-modeling'),
    ('databases', 'postgresql-jsonb-modeling'),
    ('databases', 'postgresql-partitioning'),
    ('databases', 'postgresql-vacuum-and-bloat'),
    ('databases', 'postgresql-connection-pooling'),
    ('databases', 'postgresql-backup-and-recovery'),
    ('databases', 'postgresql-replication-basics'),
    ('databases', 'postgresql-full-text-search'),
    ('databases', 'database-migrations-at-scale'),
    ('databases', 'database-contention'),
    ('databases', 'transactions-and-isolation'),
    ('databases', 'database-performance-tuning'),
    ('databases', 'jdbc-and-pool-tuning'),
    ('databases', 'migration-strategies'),
    ('databases', 'refactoring-data-and-schemas'),
    ('persistence', 'hibernate-mapping-basics'),
    ('persistence', 'hibernate-entity-lifecycle'),
    ('persistence', 'jpa-persistence-context'),
    ('persistence', 'jpa-lazy-loading-pitfalls'),
    ('persistence', 'n-plus-one-problem'),
    ('persistence', 'jpa-fetch-strategies'),
    ('persistence', 'hibernate-batch-processing'),
    ('persistence', 'jpa-locking-strategies'),
    ('persistence', 'hibernate-second-level-cache'),
    ('persistence', 'jpa-pagination-strategies'),
    ('persistence', 'hibernate-dirty-checking'),
    ('persistence', 'jpa-vs-jdbc-tradeoffs'),
    ('persistence', 'hibernate-schema-generation'),
    ('persistence', 'jpa-auditing-and-timestamps'),
    ('persistence', 'hibernate-statistics-and-tuning'),
    ('persistence', 'jpa-criteria-and-specifications'),
    ('messaging-and-events', 'kafka-architecture-brokers-topics'),
    ('messaging-and-events', 'kafka-producers-and-acks'),
    ('messaging-and-events', 'kafka-consumers-and-offsets'),
    ('messaging-and-events', 'kafka-consumer-groups-and-rebalancing'),
    ('messaging-and-events', 'kafka-partitioning-strategy'),
    ('messaging-and-events', 'kafka-delivery-semantics'),
    ('messaging-and-events', 'kafka-exactly-once-processing'),
    ('messaging-and-events', 'kafka-schema-evolution'),
    ('messaging-and-events', 'kafka-retries-and-dead-letters'),
    ('messaging-and-events', 'kafka-transactions'),
    ('messaging-and-events', 'kafka-streams-essentials'),
    ('messaging-and-events', 'kafka-connect-essentials'),
    ('messaging-and-events', 'kafka-testing-strategies'),
    ('messaging-and-events', 'event-sourcing-fundamentals'),
    ('messaging-and-events', 'cqrs-fundamentals'),
    ('messaging-and-events', 'event-schema-governance'),
    ('messaging-and-events', 'event-driven-design'),
    ('messaging-and-events', 'jms-fundamentals'),
    ('messaging-and-events', 'rabbitmq-with-spring-amqp'),
    ('messaging-and-events', 'message-ordering-and-partitioning'),
    ('messaging-and-events', 'message-idempotency'),
    ('messaging-and-events', 'poison-messages-and-dlq'),
    ('messaging-and-events', 'transactional-outbox-pattern'),
    ('messaging-and-events', 'idempotency-in-distributed-systems'),
    ('messaging-and-events', 'synchronous-vs-asynchronous-service-calls'),
    ('messaging-and-events', 'distributed-transactions-and-sagas'),
    ('integration', 'messaging-vs-http-integration'),
    ('integration', 'spring-integration-basics'),
    ('integration', 'apache-camel-for-integration'),
    ('integration', 'batch-processing-with-spring-batch'),
    ('integration', 'scheduling-and-quartz'),
    ('integration', 'file-and-ftp-integration'),
    ('integration', 'soap-and-legacy-integration'),
    ('integration', 'webhooks-outbound-and-inbound'),
    ('integration', 'email-and-notification-pipelines'),
    ('integration', 'integration-testing-across-systems'),
    ('api-design', 'http-api-contracts'),
    ('api-design', 'rest-resource-modeling'),
    ('api-design', 'openapi-first-design'),
    ('api-design', 'api-versioning-strategies'),
    ('api-design', 'api-error-contracts'),
    ('api-design', 'api-idempotency-and-safety'),
    ('api-design', 'graphql-schema-design'),
    ('api-design', 'graphql-in-java-with-spring'),
    ('api-design', 'graphql-security-and-limits'),
    ('api-design', 'grpc-and-protobuf-basics'),
    ('api-design', 'grpc-in-spring-services'),
    ('api-design', 'choosing-between-rest-graphql-grpc'),
    ('api-design', 'api-rate-limiting-and-quotas'),
    ('api-design', 'api-observability-and-analytics'),
    ('api-design', 'api-security-at-the-edge'),
    ('api-design', 'api-documentation-and-developer-experience'),
    ('api-design', 'pagination-and-filtering'),
    ('api-design', 'platform-api-design'),
    ('api-design', 'platform-evolution'),
    ('http-and-networking', 'http-methods-semantics'),
    ('http-and-networking', 'http-status-code-craft'),
    ('http-and-networking', 'http-headers-that-matter'),
    ('http-and-networking', 'http-caching-in-depth'),
    ('http-and-networking', 'http-2-and-http-3'),
    ('http-and-networking', 'tls-handshake-essentials'),
    ('http-and-networking', 'connection-reuse-and-pooling'),
    ('http-and-networking', 'timeouts-and-retry-matrix'),
    ('http-and-networking', 'proxies-and-load-balancers'),
    ('http-and-networking', 'dns-in-service-calls'),
    ('http-and-networking', 'compression-and-payload-strategies'),
    ('http-and-networking', 'websockets-and-sse'),
    ('http-and-networking', 'content-security-and-cors'),
    ('http-and-networking', 'cookie-and-session-mechanics'),
    ('http-and-networking', 'network-debugging-toolkit'),
    ('microservices', 'service-resilience'),
    ('microservices', 'service-level-objectives'),
    ('microservices', 'consistency-and-availability'),
    ('microservices', 'multi-region-consistency'),
    ('microservices', 'api-gateway-patterns'),
    ('microservices', 'service-discovery-in-practice'),
    ('microservices', 'centralised-configuration'),
    ('microservices', 'circuit-breaker-patterns'),
    ('microservices', 'bulkheads-and-pool-isolation'),
    ('microservices', 'retry-storm-prevention'),
    ('microservices', 'distributed-tracing-in-java'),
    ('microservices', 'correlation-ids-and-request-context'),
    ('microservices', 'service-contract-evolution'),
    ('microservices', 'multi-tenancy-strategies'),
    ('microservices', 'strangler-fig-migration'),
    ('microservices', 'microservices-anti-patterns'),
    ('microservices', 'contract-testing'),
    ('microservices', 'data-governance'),
    ('architecture', 'architecture-economics'),
    ('architecture', 'architecture-quality-attributes'),
    ('architecture', 'service-boundaries'),
    ('architecture', 'engineering-decision-records'),
    ('architecture', 'threat-modeling-basics'),
    ('domain-driven-design', 'ubiquitous-language-in-code'),
    ('domain-driven-design', 'strategic-domain-analysis'),
    ('domain-driven-design', 'bounded-contexts-in-practice'),
    ('domain-driven-design', 'context-mapping-patterns'),
    ('domain-driven-design', 'entities-and-identity'),
    ('domain-driven-design', 'value-objects-modeling'),
    ('domain-driven-design', 'aggregates-and-consistency-boundaries'),
    ('domain-driven-design', 'domain-services'),
    ('domain-driven-design', 'domain-events-in-the-model'),
    ('domain-driven-design', 'repositories-as-domain-abstractions'),
    ('domain-driven-design', 'factories-and-builders-in-domain-code'),
    ('domain-driven-design', 'anemic-model-anti-pattern'),
    ('domain-driven-design', 'hexagonal-architecture-and-ddd'),
    ('domain-driven-design', 'ddd-and-relational-mapping'),
    ('domain-driven-design', 'event-storming-to-code'),
    ('testing', 'testing-boundaries'),
    ('testing', 'junit5-fundamentals'),
    ('testing', 'junit5-parameterized-tests'),
    ('testing', 'junit5-extension-model'),
    ('testing', 'assertj-fluent-assertions'),
    ('testing', 'mockito-essentials'),
    ('testing', 'test-doubles-and-design'),
    ('testing', 'testcontainers-fundamentals'),
    ('testing', 'http-stubbing-with-wiremock'),
    ('testing', 'property-based-testing'),
    ('testing', 'flaky-tests-and-ci-reliability'),
    ('testing', 'approval-testing-legacy-behavior'),
    ('testing', 'architecture-tests-with-archunit'),
    ('testing', 'testing-concurrent-code'),
    ('quality-and-static-analysis', 'code-coverage-with-jacoco'),
    ('quality-and-static-analysis', 'static-analysis-quality-gates'),
    ('quality-and-static-analysis', 'mutation-testing-with-pit'),
    ('quality-and-static-analysis', 'microbenchmarking-with-jmh'),
    ('quality-and-static-analysis', 'load-testing-essentials'),
    ('quality-and-static-analysis', 'load-test-driven-tuning'),
    ('observability', 'production-observability'),
    ('observability', 'observability-three-pillars'),
    ('observability', 'structured-logging-in-java'),
    ('observability', 'log-aggregation-and-retention'),
    ('observability', 'micrometer-metrics-fundamentals'),
    ('observability', 'metric-cardinality-management'),
    ('observability', 'histogram-percentiles-and-buckets'),
    ('observability', 'prometheus-and-grafana-workflow'),
    ('observability', 'alerting-on-symptoms-not-causes'),
    ('observability', 'distributed-tracing-with-opentelemetry'),
    ('observability', 'trace-context-propagation'),
    ('observability', 'jvm-runtime-observability'),
    ('observability', 'health-checks-and-readiness-in-spring'),
    ('observability', 'profiling-in-production'),
    ('observability', 'error-tracking-and-exception-aggregation'),
    ('observability', 'incident-debugging-with-observability'),
    ('performance', 'profiling-java-services'),
    ('performance', 'caching-strategies'),
    ('performance', 'cache-consistency'),
    ('performance', 'serialization-performance'),
    ('performance', 'string-performance-java'),
    ('performance', 'collection-performance-java'),
    ('performance', 'io-and-network-performance'),
    ('performance', 'async-io-and-reactor-performance'),
    ('performance', 'performance-regression-prevention'),
    ('reactive', 'reactive-programming-mental-model'),
    ('reactive', 'reactor-core-fundamentals'),
    ('reactive', 'reactor-backpressure-in-practice'),
    ('reactive', 'reactor-error-handling'),
    ('reactive', 'reactor-context-and-threading'),
    ('reactive', 'blocking-code-in-reactive-pipelines'),
    ('reactive', 'spring-webflux-fundamentals'),
    ('reactive', 'webflux-testing-with-stepverifier'),
    ('reactive', 'r2dbc-and-reactive-persistence'),
    ('reactive', 'reactive-http-clients'),
    ('reactive', 'reactive-vs-virtual-threads'),
    ('reactive', 'streaming-data-with-kafka-and-reactor'),
    ('reactive', 'reactive-observability-and-debugging'),
    ('reactive', 'migrating-mvc-to-webflux'),
    ('reactive', 'reactive-anti-patterns'),
    ('containers-and-kubernetes', 'dockerfiles-for-java-apps'),
    ('containers-and-kubernetes', 'docker-layer-caching-for-java'),
    ('containers-and-kubernetes', 'jib-and-buildpack-strategies'),
    ('containers-and-kubernetes', 'docker-compose-for-development'),
    ('containers-and-kubernetes', 'kubernetes-deployments-and-services'),
    ('containers-and-kubernetes', 'kubernetes-configmaps-and-secrets'),
    ('containers-and-kubernetes', 'kubernetes-probes-and-health'),
    ('containers-and-kubernetes', 'kubernetes-resource-limits-jvm'),
    ('containers-and-kubernetes', 'kubernetes-hpa-scaling'),
    ('containers-and-kubernetes', 'kubernetes-jobs-and-cronjobs'),
    ('containers-and-kubernetes', 'helm-basics-for-java-services'),
    ('containers-and-kubernetes', 'kubernetes-operators-overview'),
    ('containers-and-kubernetes', 'service-mesh-essentials'),
    ('containers-and-kubernetes', 'container-image-security'),
    ('containers-and-kubernetes', 'container-registries-and-supply-chain'),
    ('containers-and-kubernetes', 'graceful-shutdown-in-containers'),
    ('cloud-and-delivery', 'twelve-factor-spring-apps'),
    ('cloud-and-delivery', 'environment-parity'),
    ('cloud-and-delivery', 'ci-cd-github-actions-java'),
    ('cloud-and-delivery', 'ci-cd-quality-gates'),
    ('cloud-and-delivery', 'blue-green-deployments'),
    ('cloud-and-delivery', 'canary-deployments'),
    ('cloud-and-delivery', 'feature-flags-in-practice'),
    ('cloud-and-delivery', 'infrastructure-as-code-terraform'),
    ('cloud-and-delivery', 'aws-managed-services-java'),
    ('cloud-and-delivery', 'azure-managed-services-java'),
    ('cloud-and-delivery', 'gcp-managed-services-java'),
    ('cloud-and-delivery', 'secrets-management-in-the-cloud'),
    ('cloud-and-delivery', 'autoscaling-strategies'),
    ('cloud-and-delivery', 'multi-environment-configuration'),
    ('cloud-and-delivery', 'cost-aware-architecture'),
    ('cloud-and-delivery', 'safe-delivery-strategies'),
    ('security', 'owasp-top-ten-for-java'),
    ('security', 'sql-injection-prevention-java'),
    ('security', 'xss-prevention-java'),
    ('security', 'csrf-protection-java'),
    ('security', 'input-validation-strategies'),
    ('security', 'secure-password-storage'),
    ('security', 'secrets-in-source-avoidance'),
    ('security', 'dependency-vulnerability-scanning'),
    ('security', 'jwt-best-practices'),
    ('security', 'oauth2-and-oidc-flows'),
    ('security', 'securing-rest-apis'),
    ('security', 'security-headers-and-csp'),
    ('security', 'cryptography-basics-for-java-devs'),
    ('security', 'security-logging-and-auditing'),
    ('security', 'supply-chain-security-slsa'),
    ('data-formats', 'json-with-jackson-basics'),
    ('data-formats', 'jackson-annotations-and-customization'),
    ('data-formats', 'jackson-polymorphic-serialization'),
    ('data-formats', 'json-schema-and-validation'),
    ('data-formats', 'xml-processing-in-java'),
    ('data-formats', 'yaml-for-configuration'),
    ('data-formats', 'csv-and-tabular-data'),
    ('data-formats', 'protocol-buffers-in-java'),
    ('data-formats', 'avro-and-schema-registry-basics'),
    ('data-formats', 'choosing-a-serialization-format'),
    ('data-formats', 'object-mapping-between-layers'),
    ('data-formats', 'deserialization-security'),
    ('data-formats', 'dates-numbers-and-locale-serialization'),
    ('data-formats', 'streaming-large-payloads'),
    ('algorithms', 'big-o-in-practice'),
    ('algorithms', 'arrays-and-strings-patterns'),
    ('algorithms', 'hashing-patterns'),
    ('algorithms', 'two-pointers-and-sliding-windows'),
    ('algorithms', 'stacks-and-queues-patterns'),
    ('algorithms', 'linked-list-patterns'),
    ('algorithms', 'trees-and-traversals'),
    ('algorithms', 'binary-search-patterns'),
    ('algorithms', 'heaps-and-top-k'),
    ('algorithms', 'graphs-basics-bfs-dfs'),
    ('algorithms', 'shortest-path-intuition'),
    ('algorithms', 'dynamic-programming-intuition'),
    ('algorithms', 'greedy-algorithms-when'),
    ('algorithms', 'recursion-and-backtracking'),
    ('algorithms', 'sorting-algorithms-in-depth'),
    ('algorithms', 'bit-manipulation-basics'),
    ('algorithms', 'choosing-data-structures-at-work'),
    ('refactoring-and-legacy', 'refactoring-safely'),
    ('refactoring-and-legacy', 'naming-and-readability'),
    ('refactoring-and-legacy', 'extracting-methods-and-classes'),
    ('refactoring-and-legacy', 'replacing-conditional-logic'),
    ('refactoring-and-legacy', 'removing-duplication-carefully'),
    ('refactoring-and-legacy', 'working-with-legacy-code'),
    ('refactoring-and-legacy', 'breaking-dependencies-in-legacy'),
    ('refactoring-and-legacy', 'incremental-framework-upgrades'),
    ('refactoring-and-legacy', 'modularizing-a-monolith'),
    ('refactoring-and-legacy', 'code-review-for-maintainability'),
    ('refactoring-and-legacy', 'eliminating-technical-debt-systematically'),
    ('refactoring-and-legacy', 'dead-code-and-orphan-removal'),
    ('refactoring-and-legacy', 'documentation-that-survives'),
    ('engineering-practice', 'reading-code-effectively'),
    ('engineering-practice', 'asking-better-technical-questions'),
    ('engineering-practice', 'writing-engineering-proposals'),
    ('engineering-practice', 'estimating-work-realistically'),
    ('engineering-practice', 'code-review-culture'),
    ('engineering-practice', 'mentoring-junior-engineers'),
    ('engineering-practice', 'on-call-healthy-practices'),
    ('engineering-practice', 'blameless-incident-reviews'),
    ('engineering-practice', 'runbooks-and-operational-readiness'),
    ('engineering-practice', 'technical-interview-preparation'),
    ('engineering-practice', 'writing-a-strong-cv'),
    ('engineering-practice', 'growing-from-junior-to-senior'),
    ('engineering-practice', 'engineering-metrics-that-help'),
    ('engineering-practice', 'stakeholder-communication'),
    ('engineering-practice', 'documentation-and-knowledge-sharing'),
    ('engineering-practice', 'career-ladders-and-growth-plans')
) AS m(category_slug, tutorial_slug)
WHERE c.slug = m.category_slug AND tutorial.slug = m.tutorial_slug;

-- Every published tutorial must sit in a category; fail loudly if the mapping drifts
-- away from the catalog instead of silently leaving lessons ungrouped.
DO $$
DECLARE
    ungrouped INTEGER;
BEGIN
    SELECT count(*) INTO ungrouped FROM tutorial WHERE category_id IS NULL;
    IF ungrouped > 0 THEN
        RAISE EXCEPTION 'V35 left % tutorial(s) without a category', ungrouped;
    END IF;
END
$$;
